# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

news = Section.create(title: 'News')
hist = Section.create(title: 'History')

Entry.create(section_id: news.id, title: 'News Title #2', content: 'News Content 2', author: 'Test')

Entry.create(section_id: hist.id, title: 'History Title #1', content: 'History Content 1', author: 'Test')
Entry.create(section_id: hist.id, title: 'History Title #2', content: 'History Content 2', author: 'Test')

Entry.create(section_id: news.id, title: 'Indian Gaming and Its Effects in Southern California', author: 'Group 5', content: '<p>The history of Indian gaming is a complicated one. For years, Indian gaming has been a hot-button issue in California with many proponents both for and against it. While there have been, and continue to be, many in depth arguments both for and against, there seems to be a roughly two sided debated raging.</p><p>On one hand, a perceived image of tribes with casinos is that they have become exceedingly wealthy and no longer need to be "taken care of" by the U.S. government. Others that can be put in this group believe that gambling itself is destructive to the community. On the other side, are those who believe that Indian gaming can be used as a way to elevate tribes out of poverty in addition to helping tribes determine their own fate. There are many examples of tribes becoming quite successful and wealthy because of the casinos that they opened; the tribes most notably in southern California are the Sycuan, Barona, and Viejas bands. In these cases, casinos have helped pull tribes out of poverty, and bring them into the modern world.</p><p>The reality, in many cases however, is that casinos are not a cure for the individual problems every tribe faces, not the least of which is public opposition to the creation of a casino. In many cases tribes barely break even or have to close down reservation casinos altogether because of their lack of revenue and foot-traffic do to the rural areas the reservations are located on.</p><p>Tribes face many challenges as they work towards full self-determination, and many see casinos and gambling as a way to help achieve that. Why are tribal run gaming casinos the focus of so much controversy; why is there so much opposition? It is time to take a look at the real economic, cultural, and religious effects of Indian casinos, both successful and otherwise, on the reservation communities associated with them.</p>')

Entry.create(section_id: news.id, title: 'Indian Gaming Legislation', url: 'http://online.liebertpub.com/doi/abs/10.1089/glr.2005.9.439', author: 'Michael May', content: '<p><span style="text-decoration: underline;"><strong>Indian Gaming Legislation</strong></span><br />The Indian Gaming Regulatory Act (IGRA) is possibly the most important piece of legislation related to Indian gaming. The act split up gaming into 3 classes with each class getting respectively harder to achieve. Class one encompasses traditional Indian gaming and small wager gambling, this is not restricted by the government. Class two includes bingo and other bingo-like games this also cannot be restricted by state government. Class three is the most controversial because it includes casino type and large wager gambling. Whether a tribe can enter into this form of gambling is dependent on individual tribal negotiations with the state. IGRA was passed in direct response to the California vs. Cabazon Band of Mission Indians Supreme Court ruling because of the confusion surrounding the legality of Indian gaming. According to IGRA, a casino can only be &ldquo;located on tribal lands acquired in trust by the Secretary of Interior &hellip; before 1988&rdquo; (Staudenmaier 439). Despite this restriction, there are some big exception that can be made for tribes that want to build on land that was taken into trust later, and this is where the controversy lies. There are six ways in which a tribe can get around this land restriction: &ldquo;1.) the lands are adjacent to lands that were in trust in 1988; 2.) lands are already located within the reservation where the tribe is now; 3.) lands are taken into trust as part of a settlement of land claim; 4.) the tribe has newly been recognized by the Secretary of Interior; 5.) lands are taken into trust as part of the restoration of lands for the tribe and the tribe has been restored to federal recognition; and lastly 6.) The Secretary of Interior takes the land into trust for the tribe&rdquo; (Staudenmaier 439-430). <br /><br /><strong>Works Cited</strong><br />Staudenmaier, Heidi McNeil, and Anne Bishop. "Reservation Shopping 101." <em>Gaming Law Review 9.5</em> (2005): 439-445.<em> Academic Search Complete</em>. Web. 14 Mar. 2013.<br /><br /></p>')

